---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: frontend/src/data/useful-info.json
  label: Info
- type: document
  path: frontend/src/data/useful-contacts.json
  label: Contacts
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/frontend/public"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start -- --port 8080 --host 0.0.0.0
